### PR TITLE
Simplify complex final alleles by splitting off any trailing reference matches

### PR DESCRIPTION
**Pull request by tsibley**
Under --haplotype-basis-alleles some datasets produced complex alleles
with trailing reference matches, such as 1X1M1X1M (in this case,
--haplotype-length was set to 1).  Alleles should be as simple as
possible and capture only the variation, so trimming trailing reference
matches is a useful noise removal step.

I believe this only manifests when reads end at the position that
generates the final 1M (using the example above), since otherwise
following alleles will eventually extend/split the complex allele in
addAllele().

There are now a few places that do this kind of splitting, so it may
want to be refactored into a method.

### CODE REVIEW

**Comment by pjotrp** [comment]
@tsibley we have three open PRs from you that have gone stale after 5 years! Sorry about that. I think they have virtue. Are you willing to take a look again and see if we should merge them? It may require rebasing with the current tree.

**Comment by tsibley** [comment]
@pjotrp Thanks for following up, even after all this time. I think my changes still have value too, but I’m no longer working on any projects that use freebayes. I’m afraid I don’t have the time to revisit these PRs anymore.

**Comment by pjotrp** [comment]
Alright. Since your branches are out of sync I will try to cherry-pick your commits. If that is not easy I will merge them as straight git patches and close the PRs.

**Comment by tsibley** [comment]
Thanks!

**Comment by pjotrp** [comment]
I merged and added the --trim-complex-tail switch so it is an opt-in. I had to patch by hand.

**Pull request closed without merging**
