### PR TITLE
search the : from the end in region specifications

### PR DESCRIPTION
**Pull request by jwbargsten**

### CODE REVIEW

**Comment by mlin** [comment]
@jwbargsten just curious could you mention the reference assembly motivating this?

**Comment by tfenne** [comment]
@mlin anyone using `hs38DH` will likely run into this as it has contigs for all the HLA alleles, named like `HLA-A*01:01:01:01`, so a region would confusingly look like `HLA-A*01:01:01:01:1-100`.

**Comment by jwbargsten** [comment]
@mlin I work in plants. Here much less stuff is standardized. In my case I received an assembly from the sequencing company with colons in the IDs. But you can also see it in publicly available genomes, if you e.g. have a look at the gene names of Micromonas pusilla CCMP1545 v3.0.

For sure I could have converted it, but first of all I would have to remap IDs every time and, secondly, I thought: perhaps other people have this problem, too. So why not solve it at the source. I had a look at samtools, there the colon is also searched from the back.

**Comment by bwlang** [comment]
I think this is no longer relevant now that #383 has been merged

**Pull request closed without merging**
