### PR TITLE
Exit entropy loop if we encounter too many consecutive Ns.

### PR DESCRIPTION
**Pull request by nh13**
Example fix for https://github.com/ekg/freebayes/issues/289

### CODE REVIEW

**Comment by nh13** [comment]
@ekg any chance you could take a look?

**Comment by ekg** [comment]
Will do!

**Comment by nh13** [comment]
@ekg bump.

**Comment by ekg** [comment]
Eyes on. Need to go manual mode to do this.

**Comment by sambrightman** [comment]
I'm not 100% sure I understand this feature, but doesn't the whole block need moving up into the conditional above? Even with a max-N condition, the right boundary is moved and used later for haplotype length. I've encountered this issue when CIGAR from BWA incorrectly marks the part of a read overlapping with the start of a very long N sequence as an insertion. As the TODO says, the code is not even certain that it has a repeat when it begins the entropy testing.

**Comment by pjotrp** [comment]
Closing this for lack of activity

**Pull request closed without merging**
