### PR TITLE
VCF's should not include IUPAC bases in the REF column.

### PR DESCRIPTION
**Pull request by nh13**
If the input FASTA contains IUPAC bases, then the output VCF may contain IUPAC base(s) in the `REF` column, in particular for indels.  The VCF spec states only `[ACGTN]` may be listed in the `REF` column. 

It may be better to do the IUPAC modification _after_ calling the variants (does FreeBayes leverage the IUPAC characters?), for example, right before writing the VCF, but I have implemented modifying the FASTA upon reading for expediency.

### CODE REVIEW

**Comment by nh13** [comment]
@ekg any change you could look at this?

**Comment by nh13** [comment]
@ekg bump

**Comment by sambrightman** [comment]
We also encountered this and would love to see it fixed. I've issued a PR to @nh13 against his PR aiming to tidy it up a little and not break the test which fails here. Maybe you could merge that and re-push this, @nh13?

**Comment by nh13** [comment]
@sambrightman I merged the PR, but it looks there are some conflicts.

**Comment by sambrightman** [comment]
Yeah, that's because of the SeqLib merge in the interim. I've fixed it but now you've merged I'm not sure what the cleanest way to incorporate it is. I've pushed again to [my version of the branch](https://github.com/sambrightman/freebayes/tree/nh_fasta_iupac). I think I can either make a new PR here in the official repo (and we close this one), or you can hard reset *your* `nh_fasta_iupac` branch to match mine, force push it and continue here in this PR. Any preference?

**Comment by nh13** [comment]
@sambrightman just make a new branch and rebase on top of mine and make a PR.  I would prefer not to have to do much more git magic.

**Comment by sambrightman** [comment]
Ok, #327 has both change sets.

**Comment by sambrightman** [comment]
With #327 merged, this can be closed.

**Comment by pjotrp** [comment]
@nh13 and @sambrightman are you willing to work with me to get this merged? The conflicts should be fairly minor.

**Comment by sambrightman** [comment]
As above, I believe #327 already covered this.

**Comment by pjotrp** [comment]
Thanks Sam! I'll close it now.

**Pull request closed without merging**
