### PR TITLE
remove makefile

### PR DESCRIPTION
**Pull request by ekg**
The makefile is no longer used, and is causing confusion.

### CODE REVIEW

**Comment by tseemann** [comment]
@ekg did you hardcode `-j 4` in that ?   that will break CIRCLE CI etc

**Comment by ekg** [comment]
In .travis.yml it's set to 4. This seems to work but maybe should be 2. I
can change it. It's not hardcoded otherwise. I'll follow your lead on how
you'd like this set up.

**Comment by tseemann** [comment]
@ekg it should always be `-j 1` really. the user gets to decide -j ?

**Comment by ekg** [comment]
In this case I'm the user, because I'm the one running the Travis ci jobs.
It's not hardcoded anywhere besides the setup for those jobs.

**Comment by pjotrp** [comment]
Makefile has been removed on my branch and added meson/ninja instructions. Will go into main soon.

**Pull request closed without merging**
