### PR TITLE
Adding snakemake example and script to split genome by bam size

### PR DESCRIPTION
**Pull request by sanjaynagi**
Regarding issue comment https://github.com/freebayes/freebayes/issues/465#issuecomment-770338345 

I have added an example snakemake .smk file (snakemake-freebayes-parallel.smk) to the /examples directory, as an example for using snakemake to parallelise freebayes. I have also added an accompanying conda environment recipe (freebayes-env.yaml), which can be used to deploy the required software automatically within snakemake. I have added a simple Rscript to the /scripts folder, which creates the region BED files. 

Lastly, I have added @travc script (split_ref_by_bai_datasize.py) to the /scripts directory. This script splits the genome into regions based on the data in bam files, useful for running jobs of equal size on clusters.

This is my first PR, so any advice is appreciated.

### CODE REVIEW

**Comment by sanjaynagi** [comment]
Apologies, Ive just noticed the original comment @pjotrp suggested editing the README, which I havent done yet. There isn't a section on parallelisation so it could be added. Would you like me to give this a go?

**Comment by pjotrp** [comment]
Yes please!

**Comment by pjotrp** [comment]
lgtm. If you add a little section on the README we can merge.

**Comment by sanjaynagi** [comment]
Hi @pjotrp . I have now added a section to the README. I placed it immediately below the examples section, where the previous bit of info regarding freebayes-parallel was. Feel free to move it of course. 

Let me know if this is OK or if you have any other suggestions.

**Comment by pjotrp** [comment]
Great! I'll add a note to the RELEASE NOTES.

**Comment by Aiswarya-prasad** [comment]
I am trying to use the snakemake example to incorporate freebayes into my own Snakemake pipeline. I ran into two issues.

1. For the rule to generate fasta regions, the command was:
```
script:
   "{params.script} --chunks --bed {params.outdir} --chromosome {params.chroms} {input.index} {params.chunks}"
```
 This throws up a name error unless instead of script I use shell as:
```
 shell:
    """
    python3 {params.script} --chunks --bed {params.outdir} --chromosome {params.chroms} {input.index} {params.chunks}
    """
```
2. The script fasta_generate_regions.py requires the argument <N> to be a number I assume. But in the command in the example, params.chunks is a list of chunks and not number of chunks. Shouldn't the command be instead,

`{params.script} --chunks --bed {params.outdir} --chromosome {params.chroms} {input.index} {params.**nchunks**}`

**Comment by Aiswarya-prasad** [comment]
Hi Sanjay! Thanks for the quick response. I am not by any means a pro but I guess I will be able to manage to submit a pull request.

As for the nameError, I think that it might be because the `script:` option does not expect to receive `{input.foo}` as an argument. 

I think that the syntax needs to be different (if it is even possible to pass arguments to script that way) or as the documentation says, the argument needs to be accepted directly from within the rule. If I understood correctly, `script:` 
should only receive path to the script. For a python script, the syntax is `snakemake.input.xxx`

My earlier suggestion to use `shell:` is probably a slightly hackier way to do it. I am not a snakemake expert but if what I think about the nameError makes sense, I can also include that change (incorporating arguments into the script rather than pass as arguments) in my pull request.

**Pull request merged**
