### PR TITLE
meson: compiler warnings, -O3 by default, don't compile C++ files twice

### PR DESCRIPTION
**Pull request by jnumm**

### CODE REVIEW

**Comment by pjotrp** [comment]
I think we went slightly out of whack here because I also updated meson. Do you mind aligning? Alternatively I'll have to merge by hand.

**Comment by pjotrp** [comment]
See https://github.com/freebayes/freebayes/commit/9feec1b2e56dbbac43ade037a3cbe95cc862d0d4

**Comment by jnumm** [comment]
I will update this PR in a few minutes.

**Comment by jnumm** [comment]
Rebased and pushed; the build failed on Travis CI but in a way that likely is not caused by this PR.

**Comment by pjotrp** [comment]
Thank you!

**Comment by pjotrp** [comment]
> Rebased and pushed; the build failed on Travis CI but in a way that likely is not caused by this PR.

It is a weird error. And only on ARM.

**Pull request merged**
